enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config
[YouTube-Morphe]
app-name = "yt"
rv-brand = "mrph"
build-mode = "both"
patches-version = "dev"
cli-version = "dev"
version = "21.03.34"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
patcher-args = "-e 'Custom branding' -OcustomName=Morpheus -e 'Theme' -OdarkThemeBackgroundColor=@android:color/black -OlightThemeBackgroundColor=@android:color/white -e 'Change package name' -OpackageName=vip.dh6k.mrph"
arch = "all"
